version: "2"
exclude_patterns:
  - "migrations/"
  - "tests/"
  - "lang/"
  - "**/*.stories.js"
  - "schemes/*.js"
plugins:
  eslint:
    enabled: true
    channel: 'eslint-5'
    config:
      config: .eslintrc.js
      extensions:
        - .js
        - .vue
  stylelint:
    enabled: true
    config:
      config: .stylelintrc.js
