dist: bionic
language: node_js
services:
  - docker
before_install:
  - sudo apt-get remove --purge -yq google-chrome-stable
  - sudo apt-get install -yq chromium-browser
before_script:
  - env > .env
script: ./tests/test-ci.sh
