# Cloud Foundry manifest
---
buildpack: nodejs_buildpack
command: "npx cservice --restartOnMemUsage 134217728 --cli false server/index.js"
domain: eu-de.cf.appdomain.cloud
memory: 512M
health-check-type: process
# health-check-http-endpoint: /robots.txt
stack: cflinuxfs3
env:
  CONSOLA_LEVEL: info
  HOST: 0.0.0.0
  OPTIMIZE_MEMORY: true
