memory: 128M
env:
  CTF_CDA_ACCESS_TOKEN: ${CTF_CDA_ACCESS_TOKEN}
  CTF_ENVIRONMENT_ID: ${CTF_ENVIRONMENT_ID}
  CTF_GRAPHQL_ORIGIN: ${CTF_GRAPHQL_ORIGIN}
  CTF_SPACE_ID: ${CTF_SPACE_ID}
  ENABLE_ITEM_EMBED_CODE: 1
  ENABLE_LINKS_TO_CLASSIC: 1
  ENABLE_SSL_NEGOTIATION: 1
  HOST: 0.0.0.0
  NUXTJS_ROBOTS: '[{"UserAgent":"Twitterbot","Disallow":""},{"UserAgent":"*","Disallow":"/"}]'
  OAUTH_CLIENT: ${OAUTH_CLIENT}
services: []
