version: "3"
services:
  nginx:
    image: europeana/portaljs-nginx
    build:
      context: ./nginx
    ports:
      - "8080:80"
      - "4433:443"
    depends_on:
      - app
  app:
    image: europeana/portaljs-app
    build:
      context: ../..
      dockerfile: ./docker/stack/app/Dockerfile
    expose:
      - "8080"
    env_file: ../../.env.docker
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - NUXT_LOADING_THROTTLE=0
  chrome-en:
    image: selenium/standalone-chrome:86.0
    environment:
      - LANG=en_GB.UTF-8
      - LANGUAGE=en_GB.UTF-8
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /dev/shm:/dev/shm
  chrome-ja:
    image: selenium/standalone-chrome:86.0
    environment:
      - LANG=ja_JP.UTF-8
      - LANGUAGE=ja_JP.UTF-8
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /dev/shm:/dev/shm
  chrome-nl:
    image: selenium/standalone-chrome:86.0
    environment:
      - LANG=nl_NL.UTF-8
      - LANGUAGE=nl_NL.UTF-8
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /dev/shm:/dev/shm
  nightwatch:
    image: europeana/portaljs-nightwatch
    build:
      context: ../../tests/features
      dockerfile: ../../docker/stack/nightwatch/Dockerfile
    depends_on:
      - nginx
      - app
      - chrome-en
      - chrome-ja
      - chrome-nl
    environment:
      - WEBDRIVER_EN_HOST=chrome-en
      - WEBDRIVER_JA_HOST=chrome-ja
      - WEBDRIVER_NL_HOST=chrome-nl
      - APP_URL=https://nginx
