version: "3"
services:
  nginx:
    image: europeana/portaljs-nginx
    build:
      context: ./nginx
    ports:
      - "8080:80"
      - "4433:443"
    networks:
      - europeana_portaljs
  app:
    image: europeana/portaljs-app
    build:
      context: ../..
      dockerfile: ./docker/stack/app/Dockerfile
    expose:
      - "8080"
    ports:
      - "3002:8080"
    environment:
      - NODE_ENV
      - ENABLE_SSL_NEGOTIATION=1
      - NIGHTWATCH_WEBDRIVER_HOST=chrome
      - HTTP_PORT=3000
      - HTTPS_PORT=3001
    env_file:
      - ../../.env
    networks:
      - europeana_portaljs
  chrome:
    image: selenium/standalone-chrome:85.0
    ports:
      - "4444:4444"
    networks:
      - europeana_portaljs
    volumes:
      - /dev/shm:/dev/shm
  # nightwatch:
  #   image: europeana/portaljs-nightwatch
  #   build:
  #     context: ../../tests/features
  #   environment:
  #     - WEBDRIVER_HOST=chrome
  #   networks:
  #     - europeana_portaljs
networks:
  europeana_portaljs:
    driver: bridge
